# Service Type for ShipBot arm operations
# dev_type: Type of device being manipulated
int8 dev_type
# dev_ori: Orientation of device rotation plane (if applicable)
int8 dev_ori
# pose: Pose of device frame to reach to
geometry_msgs/Pose pose
# turn_angle:
# * For DeviceType == B || DeviceType == V3:
# * turn_angle is either 0 or 1
# * For other rotational valves
# * turn_angle means how much end effector should turn
int64 turn_angle
---
int64 result
